apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nginx-proxy-config
spec:
  storageClassName: standard
  capacity:
    storage: 50Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/hostshare/nginx-app/proxy/config"

