apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nginx-web-content
spec:
  storageClassName: standard
  capacity:
    storage: 50Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/hostshare/nginx-app/web/content"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nginx-web-config
spec:
  storageClassName: standard
  capacity:
    storage: 50Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/hostshare/nginx-app/web/config"
