apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nginx-web-content
  namespace: ns-nginx-app
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Mi
  volumeName: pv-nginx-web-content
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nginx-web-config
  namespace: ns-nginx-app
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Mi
  volumeName: pv-nginx-web-config
